leagues: [
    'Finlandia',
    'Arabia Saudita',
    'Norvegia',
    'Austria B',
    'Polonia',
    'Croazia',
    'Danimarca B',
    'Danimarca',
    'Portogallo',
    'Svizzera B',
    'La Liga 2',
    'Premier League',
    'Irlanda',
    'Belgio',
    'Giappone B',
    'Giappone',
    'Korea',
    'Cina',
    '3. Liga',
    'Scozia',
    'Bundesliga',
    'Austria',
    'Svizzera',
    'Turchia',
    'Serie A',
    'Ligue 1',
    'Svezia',
    'Grecia',
    'Olanda',
    '2. Bundesliga',
    'Islanda',
    'La Liga',
    'Emirati Arabi',
    'Repubblica Ceca',
    'League One',
    'League Two',
    'Irlanda del Nord',
    'Olanda B',
    'Ligue 2',
    'Championship',
    'Portogallo B',
    'Serie B',
    'Primera RFEF Gruppo 2',
    'National',
    'Serie C: Girone C',
    'Serie C: Girone B',
    'Serie C: Girone A',
    'Norvegia B',
    'Primera RFEF Gruppo 1',
    'Australia',
    'Giappone A',
    'Australia (*)',
    'League Two (*)',
    'Galles'
]